language: python
python: "3.7"
os: linux
dist: bionic

compiler:
  - g++-8

addons:
  apt:
    packages:
      - g++-8

cache:
  directories:
    - $HOME/.conan/data

before_install:
  - pip install conan

install:
  - conan user

script:
  - mkdir build
  - cd build
  - CC=gcc-8 CXX=g++-8 cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - cmake --build .